export const InitialTweets = [
  {
    id: 1,
    userId: 1,
    content:
      "I am feeling great today to tweet, so I am tweeting on this broadcast Twitter clone.",
    mediaContent: "",
    likes: 5,
    isLiked: false,
    comments: [
      {
        id: 101,
        userId: 2,
        content: "This is a great tweet!",
        likes: 5,
        isLiked: false,
      },
      {
        id: 102,
        userId: 3,
        content: "Keep up the good work!",
        likes: 2,
        isLiked: false,
      },
      {
        id: 103,
        userId: 5,
        content: "Wow! its so great! i really like the content of this tweet",
        likes: 1,
        isLiked: false,
      },
    ],
    timestamp: "15:45 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 2,
    userId: 2,
    content: "Just launched my new website! Check it out! Link in my bio.",
    mediaContent: "",
    likes: 7,
    isLiked: false,
    comments: [
      {
        id: 105,
        userId: 1,
        content: "Congratulations on the launch! Your website looks amazing!",
        likes: 7,
        isLiked: false,
      },
      {
        id: 106,
        userId: 4,
        content: "Checked out your website, it's really impressive. Well done!",
        likes: 3,
        isLiked: false,
      },
    ],
    timestamp: "10:30 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 3,
    userId: 3,
    content:
      "Excited to announce my upcoming webinar on frontend development. Join me on July 25th!",
    mediaContent: "",
    likes: 52,
    isLiked: false,
    comments: [
      {
        id: 107,
        userId: 2,
        content: "I'll definitely join the webinar. Can't wait!",
        likes: 2,
        isLiked: false,
      },
    ],
    timestamp: "17:15 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 4,
    userId: 4,
    content:
      "Sharing my favorite recipe for homemade pizza. It's simply delicious!",
    mediaContent: "",
    likes: 85,
    isLiked: false,
    comments: [
      {
        id: 108,
        userId: 3,
        content: "Yum! I'm going to try making this pizza!",
        likes: 4,
        isLiked: false,
      },
      {
        id: 109,
        userId: 5,
        content: "Pizza is my favorite! Thanks for sharing the recipe.",
        likes: 1,
        isLiked: false,
      },
    ],
    timestamp: "12:20 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 5,
    userId: 5,
    content:
      "Just finished reading an amazing book. Highly recommend it to all book lovers!",
    mediaContent: "",
    likes: 25,
    isLiked: false,
    comments: [
      {
        id: 110,
        userId: 1,
        content:
          "Which book did you read? I'm looking for new recommendations.",
        likes: 3,
        isLiked: false,
      },
      {
        id: 111,
        userId: 4,
        content: "Reading is my passion too. Let's exchange book suggestions!",
        likes: 2,
        isLiked: false,
      },
    ],
    timestamp: "19:55 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 6,
    userId: 6,
    content:
      "Thrilled to announce that I've joined a new company as a frontend developer. Exciting times ahead!",
    mediaContent: "",
    likes: 85,
    isLiked: false,
    comments: [
      {
        id: 112,
        userId: 2,
        content: "Congratulations on the new role! Wishing you success.",
        likes: 4,
        isLiked: false,
      },
      {
        id: 113,
        userId: 3,
        content:
          "Great news! Looking forward to hearing about your experiences.",
        likes: 2,
        isLiked: false,
      },
    ],
    timestamp: "08:10 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 7,
    userId: 7,
    content:
      "Feeling inspired after attending a design conference. Can't wait to implement these ideas in my work!",
    mediaContent: "",
    likes: 7,
    isLiked: false,
    comments: [
      {
        id: 114,
        userId: 1,
        content:
          "Design conferences are always inspiring. Share your insights!",
        likes: 5,
        isLiked: false,
      },
    ],
    timestamp: "14:05 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 8,
    userId: 8,
    content:
      "Just released a new update for my mobile app. Download it now and let me know your feedback!",
    mediaContent: "",
    likes: 8,
    isLiked: false,
    comments: [
      {
        id: 115,
        userId: 4,
        content: "Downloaded the app and it works flawlessly! Great job!",
        likes: 8,
        isLiked: false,
      },
      {
        id: 116,
        userId: 5,
        content: "The new update has some cool features. Keep it up!",
        likes: 3,
        isLiked: false,
      },
    ],
    timestamp: "16:30 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
];
