export const InitialTweets = [
  {
    id: 1,
    userId: 1,
    content:
      "I am feeling great today to tweet, so I am tweeting on this broadcast Twitter clone.",
    mediaContent: "",
    likes: 5,
    isLiked: false,
    comments: [
      {
        id: 101,
        userId: 2,
        content: "This is a great tweet!",
        likes: 5,
        isLiked: false,
      },
      {
        id: 102,
        userId: 3,
        content: "Keep up the good work!",
        likes: 2,
        isLiked: false,
      },
      {
        id: 103,
        userId: 5,
        content: "Wow! its so great! i really like the content of this tweet",
        likes: 1,
        isLiked: false,
      },
    ],
    timestamp: "15:45 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 2,
    userId: 2,
    content: "Just launched my new website! Check it out! Link in my bio.",
    mediaContent: "",
    likes: 7,
    isLiked: false,
    comments: [
      {
        id: 105,
        userId: 1,
        content: "Congratulations on the launch! Your website looks amazing!",
        likes: 7,
        isLiked: false,
      },
      {
        id: 106,
        userId: 4,
        content: "Checked out your website, it's really impressive. Well done!",
        likes: 3,
        isLiked: false,
      },
    ],
    timestamp: "10:30 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 3,
    userId: 3,
    content:
      "Excited to announce my upcoming webinar on frontend development. Join me on July 25th!",
    mediaContent: "",
    likes: 52,
    isLiked: false,
    comments: [
      {
        id: 107,
        userId: 2,
        content: "I'll definitely join the webinar. Can't wait!",
        likes: 2,
        isLiked: false,
      },
    ],
    timestamp: "17:15 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 4,
    userId: 4,
    content:
      "Sharing my favorite recipe for homemade pizza. It's simply delicious!",
    mediaContent: "",
    likes: 85,
    isLiked: false,
    comments: [
      {
        id: 108,
        userId: 3,
        content: "Yum! I'm going to try making this pizza!",
        likes: 4,
        isLiked: false,
      },
      {
        id: 109,
        userId: 5,
        content: "Pizza is my favorite! Thanks for sharing the recipe.",
        likes: 1,
        isLiked: false,
      },
    ],
    timestamp: "12:20 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 5,
    userId: 5,
    content:
      "Just finished reading an amazing book. Highly recommend it to all book lovers!",
    mediaContent: "",
    likes: 25,
    isLiked: false,
    comments: [
      {
        id: 110,
        userId: 1,
        content:
          "Which book did you read? I'm looking for new recommendations.",
        likes: 3,
        isLiked: false,
      },
      {
        id: 111,
        userId: 4,
        content: "Reading is my passion too. Let's exchange book suggestions!",
        likes: 2,
        isLiked: false,
      },
    ],
    timestamp: "19:55 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 6,
    userId: 6,
    content:
      "Thrilled to announce that I've joined a new company as a frontend developer. Exciting times ahead!",
    mediaContent: "",
    likes: 85,
    isLiked: false,
    comments: [
      {
        id: 112,
        userId: 2,
        content: "Congratulations on the new role! Wishing you success.",
        likes: 4,
        isLiked: false,
      },
      {
        id: 113,
        userId: 3,
        content:
          "Great news! Looking forward to hearing about your experiences.",
        likes: 2,
        isLiked: false,
      },
    ],
    timestamp: "08:10 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 7,
    userId: 7,
    content:
      "Feeling inspired after attending a design conference. Can't wait to implement these ideas in my work!",
    mediaContent: "",
    likes: 7,
    isLiked: false,
    comments: [
      {
        id: 114,
        userId: 1,
        content:
          "Design conferences are always inspiring. Share your insights!",
        likes: 5,
        isLiked: false,
      },
    ],
    timestamp: "14:05 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 8,
    userId: 8,
    content:
      "Just released a new update for my mobile app. Download it now and let me know your feedback!",
    mediaContent: "",
    likes: 8,
    isLiked: false,
    comments: [
      {
        id: 115,
        userId: 4,
        content: "Downloaded the app and it works flawlessly! Great job!",
        likes: 8,
        isLiked: false,
      },
      {
        id: 116,
        userId: 5,
        content: "The new update has some cool features. Keep it up!",
        likes: 3,
        isLiked: false,
      },
    ],
    timestamp: "16:30 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 9,
    userId: 9,
    content:
      "Started learning a new programming language today. Excited to expand my skills!",
    mediaContent: "",
    likes: 89,
    isLiked: false,
    comments: [
      {
        id: 117,
        userId: 2,
        content: "Learning new languages is always exciting. Which one?",
        likes: 6,
        isLiked: false,
      },
      {
        id: 118,
        userId: 3,
        content: "Best of luck! You'll pick it up quickly.",
        likes: 1,
        isLiked: false,
      },
    ],
    timestamp: "11:40 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 10,
    userId: 10,
    content:
      "Exploring a new hiking trail this weekend. Nature and adventure await!",
    mediaContent: "",
    likes: 85,
    isLiked: false,
    comments: [
      {
        id: 119,
        userId: 1,
        content: "Enjoy the hike! Nature is always refreshing.",
        likes: 5,
        isLiked: false,
      },
    ],
    timestamp: "09:50 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 11,
    userId: 11,
    content:
      "Attended an insightful tech meetup today. Learned a lot and met some amazing people!",
    mediaContent: "",
    likes: 45,
    isLiked: false,
    comments: [
      {
        id: 120,
        userId: 2,
        content:
          "Tech meetups are great for networking. Any exciting takeaways?",
        likes: 3,
        isLiked: false,
      },
      {
        id: 121,
        userId: 3,
        content: "Glad you had a good time. Looking forward to the next one!",
        likes: 1,
        isLiked: false,
      },
    ],
    timestamp: "18:20 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 12,
    userId: 12,
    content:
      "Just launched a new podcast! Tune in to hear interesting discussions on tech and innovation.",
    mediaContent: "",
    likes: 52,
    isLiked: false,
    comments: [
      {
        id: 122,
        userId: 4,
        content: "Just subscribed to your podcast. Looking forward to it!",
        likes: 7,
        isLiked: false,
      },
      {
        id: 123,
        userId: 5,
        content: "Congratulations on the launch! I'll definitely tune in.",
        likes: 2,
        isLiked: false,
      },
    ],
    timestamp: "13:05 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 13,
    userId: 1,
    content:
      "Enjoying a relaxing weekend with my family. Quality time well spent!",
    mediaContent: "",
    likes: 58,
    isLiked: false,
    comments: [
      {
        id: 124,
        userId: 1,
        content: "Family time is precious. Enjoy your weekend!",
        likes: 8,
        isLiked: false,
      },
    ],
    timestamp: "10:15 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 14,
    userId: 2,
    content:
      "Sharing my top tips for effective time management. Stay productive and achieve your goals!",
    mediaContent: "",
    likes: 78,
    isLiked: false,
    comments: [
      {
        id: 125,
        userId: 2,
        content: "Time management is key to productivity. Thanks for the tips!",
        likes: 10,
        isLiked: false,
      },
    ],
    timestamp: "14:30 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 15,
    userId: 3,
    content:
      "Just finished a challenging coding project. Celebrating with a cup of coffee!",
    mediaContent: "",
    likes: 7,
    isLiked: false,
    comments: [
      {
        id: 126,
        userId: 8,
        content: "Congrats on completing the project! Celebrate and relax!",
        likes: 5,
        isLiked: false,
      },
    ],
    timestamp: "16:55 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 16,
    userId: 4,
    content:
      "Excited to start my new blog series on UI/UX design principles. Stay tuned for insightful articles!",
    mediaContent: "",
    likes: 89,
    isLiked: false,
    comments: [
      {
        id: 127,
        userId: 7,
        content: "Looking forward to your UI/UX articles. Informative content!",
        likes: 3,
        isLiked: false,
      },
    ],
    timestamp: "11:10 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 17,
    userId: 5,
    content:
      "Attended a fascinating workshop on data analytics. Ready to apply new techniques in my work!",
    mediaContent: "",
    likes: 22,
    isLiked: false,
    comments: [
      {
        id: 128,
        userId: 5,
        content: "Data analytics is fascinating. Share your learnings!",
        likes: 4,
        isLiked: false,
      },
    ],
    timestamp: "13:45 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 18,
    userId: 6,
    content:
      "Just released an open-source library for React developers. Check it out on GitHub!",
    mediaContent: "",
    likes: 36,
    isLiked: false,
    comments: [
      {
        id: 129,
        userId: 1,
        content: "Thanks for contributing to the community. Great work!",
        likes: 6,
        isLiked: false,
      },
    ],
    timestamp: "10:05 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 19,
    userId: 7,
    content:
      "Feeling grateful for the support and encouragement from the developer community. Thank you all!",
    mediaContent: "",
    likes: 6,
    isLiked: false,
    comments: [
      {
        id: 130,
        userId: 2,
        content: "Good luck with the coding challenge! You'll ace it!",
        likes: 3,
        isLiked: false,
      },
    ],
    timestamp: "12:50 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
  {
    id: 20,
    userId: 8,
    content:
      "Started a new coding challenge on a popular coding platform. Excited to test my skills!",
    mediaContent: "",
    likes: 25,
    isLiked: false,
    comments: [
      {
        id: 131,
        userId: 3,
        content: "Have a wonderful time on the hiking trail. Enjoy nature!",
        likes: 7,
        isLiked: false,
      },
    ],
    timestamp: "15:20 PM",
    date: "Jul 24, 2023",
    bookmark: false,
  },
];
